### ISSUE TITLE
Error on Windows Install

### ISSUE THREAD

**Issue by joefedorowicz** [bwiley1/pandleau#15]
Hello, 

This works on my Mac side but not on my windows side. I seemingly installed everything correctly. 

Traceback (most recent call last):
  File ".\helpscout.py", line 73, in <module>
    df_tableau.to_tableau('PATH\helpscout30.hyper', add_index=False)
  File "C:\PATH\lib\site-packages\pandleau-0.3.1-py3.7.egg\pandleau\pandle
au.py", line 112, in to_tableau
    new_extract = Extract( path )
  File "C:\PATH\lib\site-packages\tableausdk\HyperExtract.py", line 594, i
n __init__
    raise Exceptions.TableauException(ret, Exceptions.GetLastErrorMessage())
tableausdk.Exceptions.TableauException: TableauException (999): Unknown error

**Comment by bwiley1** [comment]
Hi joefedorowicz,

Thanks for opening this issue. It looks like this is an error with the Tableau SDK and not necessarily the pandleau code - do you receive the same error testing other datasets?

**Comment by joefedorowicz** [comment]
I can check it shortly. The same code works on the Mac side which was weird. I’ll dig further. Thanks.

JOE FEDOROWICZ
HARMELIN MEDIA | SR. SYSTEMS ADMINISTRATOR
t: 484.270.9541 c: 215.738.1489

________________________________

**Comment by bwiley1** [comment]
Hi joefedorowicz,

Any more insight on this error? If not, I'll go ahead and close this issue. Thanks!
