### ISSUE TITLE
TableauException (303): extract path must have .tde extension

### ISSUE THREAD

**Issue by philip-zelichenko** [bwiley1/pandleau#9]
first of all, thanks for a great tool.

second, i'm getting the following error:
>>> df_tableau = pandleau(example_df)
>>> df_tableau.to_tableau('test.hyper', add_index=False)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/philipzelichenko/Downloads/pandleau-master/pandleau/pandleau.py", line 112, in to_tableau
    new_extract = Extract( path )
  File "/usr/local/lib/python3.6/site-packages/tableausdk/Extract.py", line 594, in __init__
    raise Exceptions.TableauException(ret, Exceptions.GetLastErrorMessage())
tableausdk.Exceptions.TableauException: TableauException (303): extract path must have .tde extension

any idea why?

**Comment by bwiley1** [comment]
Hi Philip,

Thanks for the positive feedback!

It looks like this error was generated because the code is referencing the .tde installation of tableausdk. Just to verify, have you installed the Extract API 2.0 from Tableau to write .hyper files? 

- https://onlinehelp.tableau.com/current/api/extract_api/en-us/help.htm#Extract/extract_api_installing.htm%3FTocPath%3D_____3

I will take a look at this and try to recreate the error this evening. Thanks for pointing this out!
